dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1
  - jruby-9.2
before_install:
  - gem install rubygems-update -N -v '<3' && update_rubygems
  - gem update bundler
script:
  - bundle exec rake test_with_coveralls